// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqvFdugFv6F00Tjjrf-2maT4MQuDlxsx0',
    appId: '1:858718782821:web:7d3319d306bbf0e6290d8c',
    messagingSenderId: '858718782821',
    projectId: 'ai-saas-application-13eaa',
    authDomain: 'ai-saas-application-13eaa.firebaseapp.com',
    storageBucket: 'ai-saas-application-13eaa.appspot.com',
    measurementId: 'G-BMGJF1DFQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpTgjRTz3mVH68YcxQ-4lTgsFHYwpUz64',
    appId: '1:858718782821:android:6691f6c3e8299c4e290d8c',
    messagingSenderId: '858718782821',
    projectId: 'ai-saas-application-13eaa',
    storageBucket: 'ai-saas-application-13eaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo2LR_lIuhG3bpike05CaRXfmcmPAhk60',
    appId: '1:858718782821:ios:7f332d462ca40938290d8c',
    messagingSenderId: '858718782821',
    projectId: 'ai-saas-application-13eaa',
    storageBucket: 'ai-saas-application-13eaa.appspot.com',
    iosBundleId: 'com.example.aiSaasApplication',
  );
}
